Make LightQueue and derivatives subscriptable
Since Python 3.9, queue.Queue is subscriptable [1]:

  import queue
  a: queue.Queue[int] = queue.Queue()
  a.put(123)

By adding evenlet, this gets monkey patched:

  import evenlet
  eventlet.monkey_patch()

  import queue
  a: queue.Queue[int] = queue.Queue()
  a.put(123)

However, when this happens, things break:

  Traceback (most recent call last):
    File "/tmp/foo/test.py", line 5, in <module>
      a: queue.Queue[int] = queue.Queue()
         ~~~~~~~~~~~^^^^^
  TypeError: type 'Queue' is not subscriptable

Resolve this by allowing the class to be parameterized.

[1] https://bugs.python.org/issue33315
[2] https://docs.python.org/3/reference/datamodel.html#object.__class_getitem__

Signed-off-by: Stephen Finucane <stephen@that.guru>
Closes: #1026