Issue #526: Make GreenSSLSocket override _create() with a fix.
Remove GreenSSLContext.wrap_socket() override, which
blows up with the original
TypeError: wrap_socket() got an unexpected keyword argument '_context'
exception. Instead, set GreenSSLContext.sslsocket_class to GreenSSLSocket,
which obviates the wrap_socket() override.

Also, for Python 3.7, remove GreenSSLSocket.__new__() override, which blows up
because SSLSocket._create() calls __new__() with (default) socket=None.

Python 3.7's SSLSocket._create() does the heavy lifting of instantiating
SSLSocket, whose __init__() method unconditionally raises TypeError to
discourage hand-constructing SSLSocket. Unfortunately, from SSLSocket's
subclass GreenSSLSocket, _create()'s super(SSLSocket, self).__init__(...) call
reaches SSLSocket.__init__(), producing that TypeError. Replicate base-class
_create() into GreenSSLSocket, except directly call socket.socket.__init__(),
which that call is intended to reach.