Fix greendns for dnspython 2.3.0+
dnspython added more type annotations in 2.3.0 -- because of how we
reimport the package piece by piece, though, not all of the types would
be available during reimport, leading to AttributeErrors like

   module 'dns.rdtypes' has no attribute 'ANY'

Now, do all of our rdtypes special-handling *first*, before reimporting
any other submodules.

Addresses #781